### ISSUE TITLE
onEnded event not firing after video has completed

### ISSUE THREAD

**Issue by tobiasbueschel** [cloudflare/stream-react#10]
I've embedded the `stream-react` component into a React application in the following way:

```jsx
<Stream
  preload
  controls
  streamRef={streamPlayerRef}
  src={myVideoID}
  onEnded={(event) => console.log(event)} // does not fire after the video finishes
  onTimeUpdate={(event) => console.log(event)} // other events work fine such as 'onTimeUpdate'
/>
```

And while I can play videos just fine, any `onEnded` event is not firing after finishing a video - and despite the fact that I can see the event handler registered to the DOM element. Instead, I see an endless loop of failed requests with a status code 404 in the dev console + my previous video being blacked out with a loading spinner on the top:

```
GET https://videodelivery.net/<redacted>/video/240/seg_497.ts?p=<redacted>&s=<redacted>
GET https://videodelivery.net/<redacted>/video/360/seg_497.ts?p=<redacted>&s=<redacted>
GET https://videodelivery.net/<redacted>/video/480/seg_497.ts?p=<redacted>&s=<redacted>
GET https://videodelivery.net/<redacted>/video/720/seg_497.ts?p=<redacted>&s=<redacted>
```

When I then look at the `streamPlayerRef`, I notice the following after finishing the video:
<img src="https://user-images.githubusercontent.com/13087421/97917086-e507fe80-1d8e-11eb-93da-d70b1fe102a6.png" width="300px" />

**Question: is this a bug with the `stream-react` wrapper or does it perhaps have anything to do with using the free tier?**

----
**My environment:**
```
"@cloudflare/stream-react": "^0.1.5",
"react-dom": "^16.13.1",
"react-router-dom": "^5.2.0",
"react-scripts": "^3.4.4",

node: v15.0.1
npm: 6.14.8
```

**Comment by third774** [comment]
Hey there! 👋  Thanks for reporting!
This definitely shouldn't have anything to do with the subscription level. Would you mind putting together a repro on https://codesandbox.io/ ?

Also, what browser/OS are you seeing this in?

**Comment by tobiasbueschel** [comment]
Here's the link:
- https://codesandbox.io/s/suspicious-feistel-0k8y8?file=/src/App.tsx
- Browser: Version 86.0.4240.111

**Chrome console screenshot:**
![image](https://user-images.githubusercontent.com/13087421/97920059-d4a65280-1d93-11eb-88cb-c2dae984d885.png)

Notice how Chrome also warns about:
```Error: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.```

**Safari (v14.0) screenshot:**
![image](https://user-images.githubusercontent.com/13087421/97920178-0ae3d200-1d94-11eb-9ada-c6ac9806ac00.png)
![image](https://user-images.githubusercontent.com/13087421/97920196-12a37680-1d94-11eb-8e9a-95c4559da778.png)

---

=> Safari works, seems like it's only a Chrome issue!

**Comment by third774** [comment]
It looks like (at least in the debug view here: https://0k8y8.csb.app/) it's consistently firing `onEnded` in Chrome. The main codesandbox window/editor seems to be having some issues today, so I'm not able to reliably test there.

Are you still able to reproduce this?
