### ISSUE TITLE
Support for closed captions

### ISSUE THREAD

**Issue by rnewton** [cloudflare/stream-react#11]
We have a home spun version of the video client because we need support for closed captioning (specifically .vtt files). Is this feature planned for the official client?

**Comment by renandincer** [comment]
Closed captioning is already supported!
Here's instructions on how to use .vtt files with Stream: https://developers.cloudflare.com/stream/uploading-videos/adding-captions

**Comment by serranoarevalo** [comment]
@renandincer is there any way to have a caption turned on by default?

**Comment by renandincer** [comment]
@serranoarevalo I don’t believe there is a public API for this. Could you please open a new issue so we can figure out?
