### ISSUE TITLE
Allow captions to be enabled by default.

### ISSUE THREAD

**Issue by serranoarevalo** [cloudflare/stream-react#12]
It would be great if there was a way to set captions of a specific language to be enabled by default.

**Comment by serranoarevalo** [comment]
Is this something you guys will work on or should I try to find a workaround?

**Comment by renandincer** [comment]
Yep. We're planning to address this. Some users from community.cloudflare.com are also asking for a similar feature. 
Right now we're focused on fixing the mobile and touchscreen device experience -- after that's finished we're planning to introduce a feature to select captions via the player API.

**Comment by daghendrik** [comment]
Awesome. Hope this will be available for the Angular component as well :-)

**Comment by renandincer** [comment]
Yep! React, angular and web over iframes.

**Comment by TuureKaunisto** [comment]
For us having captions in the language the user has selected on by default is a requirement so we're looking forward to this feature so that we can switch from our current solution to Cloudflare Stream.

**Comment by TuureKaunisto** [comment]
Has there been any progress with this issue or is there some initial plan when this might get implemented?

**Comment by serranoarevalo** [comment]
Maybe now that there is a new IFrame player this can be implemented?

**Comment by TuureKaunisto** [comment]
Is there something we can do to help? I'd be happy to make a PR for passing e.g. `captions=en` parameter to the iframe if it helps get this implemented sooner.

Not being able to have captions on by default in the users selected language is blocking us from starting to use CloudFlare stream properly. Workaround suggestions are also welcome. :)

**Comment by third774** [comment]
The `defaultTextTrack` prop is now available in [v1.1.0](https://github.com/cloudflare/stream-react/releases/tag/v1.1.0)!
