### ISSUE TITLE
Fullscreen button always disabled in Chrome (but Firefox and Safari)

### ISSUE THREAD

**Issue by meldron** [cloudflare/stream-react#17]
In Chrome the Fullscreen button is always disabled if I add the stream with:

```tsx
<Stream
    controls
    src="videoId"
    poster="/images/video_thumbnail.jpg"
   onEnded={videoEndedListener}
/>
```

Firefox and Safari work as expected.

**Comment by third774** [comment]
Hey @meldron! Thanks for reporting! Can you please share a link to a reproduction of the issue along with the OS and version of Chrome you're using?

**Comment by meldron** [comment]
Hey @third774,

I am terribly sorry, I totally forgot about the `Feature-Policy` HTTP Header.

Our setup was 

```
Feature-Policy: fullscreen 'self' ;
```

I will prepare a PR with a note about `Feature-Policy` and `Content-Security-Policy` (`script-src` and `frame-src` are needed there)

Sorry about that one.

**Comment by third774** [comment]
All good — no worries. Glad you got it sorted out!
