### ISSUE TITLE
Poster is not updating when switching between videos

### ISSUE THREAD

**Issue by JavierMartinz** [cloudflare/stream-react#19]
We are using navigation between videos and the poster is not updating when navigating from one to another. The poster shown is always the first. I've prepared a codesandbox to reproduce it:

https://codesandbox.io/s/ecstatic-swartz-oygzj

**Comment by icastillejogomez** [comment]
I'm watching your codesanbox and the poster is refreshing when switch the video

**Comment by JavierMartinz** [comment]
![cloudflare poster](https://user-images.githubusercontent.com/1155507/115354420-e51f7d80-a1b9-11eb-93e2-56c9be7d72ed.gif)

**Comment by third774** [comment]
This should be resolved with https://github.com/cloudflare/stream-react/releases/tag/v1.0.0!
