### ISSUE TITLE
React Native Support

### ISSUE THREAD

**Issue by seamive** [cloudflare/stream-react#20]
Any milestone to make this work with react native? 

---
name: feature-request
about: Use this template to request new features.
title: 'Feature request'
labels: feature-request

---

**Comment by renandincer** [comment]
Hey! We don't have plans to support react native through this package.

You can use the https://github.com/react-native-video/react-native-video package with the .m3u8 URLs you can get from the Stream API to use Stream in your native app.

**Comment by seamive** [comment]
What about captions?

**Comment by renandincer** [comment]
Captions will work out of the box, they're included in the m3u8 URL.

**Comment by third774** [comment]
Note that you'll need to upload the captions via the API
https://developers.cloudflare.com/stream/uploading-videos/adding-captions

**Comment by seamive** [comment]
@renandincer @third774: We are using HLS for Android & iOS using https://github.com/react-native-video/react-native-video as suggested. However, as per their package, https://github.com/react-native-video/react-native-video/issues/1511#issuecomment-471532172 we need to have VTT or subtitle/caption support within the HLS itself not out of the box. `"Sidecar text tracks are only supported for individual files, not HLS playlists. For HLS, you should include the text tracks as part of the playlist."`

Also, you said that 

> "Captions will work out of the box, they're included in the m3u8 URL.",

 can you guide us on how can we show them with an example with react-native-video itself?

Thanks!

**Comment by IamMasterWayne** [comment]
**How "Captions will work out of the box, if they're included in the m3u8 URL." ?**
