### ISSUE TITLE
401 on playerEnhancementInfo.json endpoint

### ISSUE THREAD

**Issue by icastillejogomez** [cloudflare/stream-react#28]
Hi everyone,

sorry I this post doesn't meet the standards or patterns. I just developed my signed urls and everything works as expected but the endpoint `https://videodelivery.net/2fa5ec943c53ac2928b511fea95abff2/metadata/playerEnhancementInfo.json` response me with 401 status code. 

What can be the cause of this? Should I be concerned? I would like free errors platform (hehe)

Thanks for all team!

**Comment by renandincer** [comment]
Hey @icastillejogomez you're right! This seems to be a bug. We're on it!

**Comment by icastillejogomez** [comment]
There is a plan to handle this bug in the current roadmap @renandincer ?

**Comment by renandincer** [comment]
We're working on it right now! :)

**Comment by third774** [comment]
@icastillejogomez this is fixed!
