### ISSUE TITLE
Height And Width Don't seem to work

### ISSUE THREAD

**Issue by shantiscript** [cloudflare/stream-react#30]
HI, when setting the height and the width in the player

```
 <Stream
          streamRef={ref}
          src={item.videoId}
          autoplay={true}
          muted={mute}
          controls={false}
          loop={true}
          onCanPlay={() => setPlaceHolder(false)}
          height="720"
          width="1280"
/>
```

the values don't seem to effect the size of the actual iframe thats rendered
while this is working when using the iframe directly, without using the react component

```
<iframe
        title="baba"
        src="https://iframe.videodelivery.net/3dc082cc5149aea41970edec72544bca?muted=true&preload=true&loop=true&autoplay=true&controls=false"
        style={{
          border: "none",
          position: "",
          top: "0",
          height: "100vh",
          width: "100vh",
        }}
        allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;"
        allowfullscreen="true"
      ></iframe> 
```

this will actually adapt the size of the iframe

**Comment by kaldenficklin** [comment]
As a work around I wrapped the Stream component in a wrapper that targets the iframe, and video tags. Hoping to have the height and weight props working properly soon

`
  width: 100%;
  height: 640px;
  overflow: hidden;

  iframe,
  video {
    width: 100% !important;
    height: 640px !important;
  }
`

**Comment by third774** [comment]
Hey, there! The `height` and `width` props set the `height` and `width` attributes on the `<iframe />` which only accepts pixel values. If you'd like more control over the styles, disable the `responsive` prop and set a `className` prop which is applied to the `<Stream />` element's container, and target the container and the iframe within it.

https://codesandbox.io/s/fervent-ganguly-wkiwb?file=/src/App.tsx

This could have been more clear in the docs — I'll update with an example. Thanks!

**Comment by kaldenficklin** [comment]
Ah if I add the prop responsive={false} the height and width props work as expected
