### ISSUE TITLE
Feature request: Showing and hiding controls via the api and being able to select which controls are shown

### ISSUE THREAD

**Issue by TuureKaunisto** [cloudflare/stream-react#31]
We'd like to show the video controls by default when a user enters the page with the video on it and not only on mouseover.

Also, for our non-technical users the video resolution and cogwheel button may be confusing and an option to hide them altogether e.g. via the player properties would be great.

**Comment by fandy** [comment]
I believe this is already possible with the `controls` prop @TuureKaunisto
