### ISSUE TITLE
pausing and playing VAST vidoes

### ISSUE THREAD

**Issue by jamienk** [cloudflare/stream-react#36]
When I use `adUrl` to load a VAST video, I lose the ability to pause or otherwise control it. 

https://codesandbox.io/s/elated-nightingale-zy178?file=/src/App.tsx

Is this a VAST issue? Or is it something stream-react is failing at...?

**Comment by third774** [comment]
This is an issue in the Stream player and we're looking to address it soon!

**Comment by third774** [comment]
This is fixed! Thank you for reporting!
