### ISSUE TITLE
For some users the player automatically pauses after ~1 second of playback

### ISSUE THREAD

**Issue by TuureKaunisto** [cloudflare/stream-react#37]
On Mac OS + Chrome, for some users the player automatically pauses after 1-2 seconds of playback without any user interaction. The video does the same thing after seeking and seems to get stuck if the user seeks beyond what has been buffered. No JS errors appear in the console.

Opening the page in an incognito window or restarting the browser seems to help but this has happened to multiple people so it seems to be more than just a fluke. Might this be a `sessionStorage` issue?

Here's a video of the issue.

https://user-images.githubusercontent.com/8841825/131503623-e8e0800b-b7d5-487a-a06e-34261a385fe8.mp4

We're using stream-react 1.2.0.

**Comment by third774** [comment]
@TuureKaunisto — thanks for reporting! Can you please share a sandbox on https://codesandbox.io/ where you can reproduce the issue? Also, what version of Chrome and MacOS are you seeing this behavior in?

**Comment by TuureKaunisto** [comment]
In the initial tests we were running the latest version of chrome at the time (92.0.4515.159)
- Chrome on macOS 10.14.6
- Brave Version 1.28.106 Chromium: 92.0.4515.159 (Official Build) (arm64) on macOS 11.3 (20E232)

Reproducing this has been really difficult since it happens only randomly. We've since then tested that the same thing happens to native html5 videos so clearly the issue is not with stream-react so I'll close this issue. If however you do have ideas what on earth might be happening or how to prevent it, feel free to send me a message. :)
