### ISSUE TITLE
Custom full-screen button

### ISSUE THREAD

**Issue by Copser** [cloudflare/stream-react#38]
Hello all,

I'm using your player but I needed to create custom controls for it, and I'm a bit stuck with a full-screen (resize) button. I'm looking at the documentation and I only see `width` and `height` for resizing the video.

I have also poke around the code and I saw this part using the `resize` event.
 
```
  useEvent("resize", ref, () => {
    if (ref.current) {
      const { videoHeight, videoWidth } = ref.current;
      setVideoDimensions({ videoHeight, videoWidth });
      onResize && onResize();
    }
  });
```
Is this is the event for resizing the video? What will be the preferred way of doing this? 

I have created a [sandbox](https://codesandbox.io/s/immutable-https-n53rw?file=/src/App.js) with some of the controls and I have added simple styling (sorry for poor CSS styling here 😄 ).

Cheers

**Comment by Copser** [comment]
This is so embarrassing, I bet you had a good laugh, I know I did 🤦 . I have used Javascript [`requestFullScreen`](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullScreen#examples) on my element, and build a logic according to that. I have updated my example but sandbox does not allow it, nevertheless, I have solved my problem, will close this issue, ☮️ .

**Comment by third774** [comment]
No worries! Sorry for the delay! One thing I'd recommend though — you'll likely end up wanting to use a library like [fscreen](https://www.npmjs.com/package/fscreen) for the fullscreen API because cross browser support is a mess. So much so that the [MDN docs recommend it](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API).
