### ISSUE TITLE
Play Icon is still on the screen after clicking "play" in Chrome and Firefox

### ISSUE THREAD

**Issue by iljaiwjew** [cloudflare/stream-react#48]
Component is very good and suitable as out-of-the-box solution but there is a little bug that worsens UX. When I start to play live stream big play button is still on the screen even after clicking  "play". It disappears after video starting. This bug is reproduced on Chrome and Firefox(mac os). In Safari everything is ok - after clicking play loader is shown.

**Comment by third774** [comment]
@iljaiwjew is this issue still present?

**Comment by third774** [comment]
Closing for now. Please let us know if you still see this issue.
