### ISSUE TITLE
Specifying Signed URL results in downloading the manifest m3u8 file

### ISSUE THREAD

**Issue by GregorioDiStefano** [cloudflare/stream-react#52]
Hi,

if you specify the signed url in `src` -- the manifest file is simply downloaded by Chrome and the player does nothing. Is this a bug or am I doing something wrong?

**Comment by third774** [comment]
@GregorioDiStefano would you mind sharing an example on https://codesandbox.io? Thanks!

**Comment by third774** [comment]
Closing for now. Please re-open an issue or comment if you're able to reproduce this.
