### ISSUE TITLE
Inspecting error from onError callback

### ISSUE THREAD

**Issue by prestonp** [cloudflare/stream-react#53]
Hello 👋 ! We've been using the @cloudflare/stream-react package and observed some videos which triggered the `onError` prop:

https://github.com/cloudflare/stream-react/blob/master/src/types.ts#L211-L214

How can we introspect what the error is? The onError function does not seem to communicate what the error is, is there another mechanism for us to understand what went wrong?

**Comment by third774** [comment]
👋🏻 Hey, @prestonp! We don't currently expose detailed information about the error that occurred, but all errors that trigger this are fatal. You could potentially respond by giving the user an option to re-load the player, but if these errors are happening consistently please share the video ID's so we can investigate!

**Comment by prestonp** [comment]
Thank you so much for the quick reply!! 

I'll have to think over the UX but the videos that triggered onError are currently working for me. So it could be a transient issue and a player reload may suffice.
