### ISSUE TITLE
letterboxColor not supported

### ISSUE THREAD

**Issue by dctanner** [cloudflare/stream-react#57]
When using responsive I get 1px black borders at certain page widths:
<img width="539" alt="CleanShot 2022-03-25 at 16 03 10@2x" src="https://user-images.githubusercontent.com/227/160157648-b0980b65-38dc-4103-af68-0fba41226a96.png">

I presume setting letterboxColor="white" would solve this, but I don't see that param supported in this lib. Can we add it in?

**Comment by third774** [comment]
Heyo — thanks for reporting! Yes, we'll get this added soon. 🙏🏻

**Comment by third774** [comment]
Also, as a side note — I'd recommend `letterboxColor="transparent"` instead of `white` for this. It will solve the problem in your page when the video is not fullscreen, but the letterboxing will still be black when a user enters fullscreen.
