### ISSUE TITLE
Add streamRef in props documentation

### ISSUE THREAD

**Issue by michaellimair** [cloudflare/stream-react#6]
Hi Cloudflare Team,

Thank you so much for the great plugin! I really appreciate that this plugin works great out of the box. However, I would like to suggest adding the `streamRef` attribute as part of the documentation. This would be really helpful for future devs who would like to access the stream reference.

Once again, thanks so much!

**Comment by morkro** [comment]
I am not sure how to make this work with TypeScript though. My code looks currently like this:

```js
function SuperComponent () {
  const streamPlayerRef = useRef<HTMLVideoElement>(null)
  
  return (
    <Stream
      preload
      controls
      width="300px"
      height="150px"
      streamRef={streamPlayerRef}
      src="xxx"
    />
  )
}
```

But `streamRef` complains with the following

> Type 'RefObject<HTMLVideoElement>' is not assignable to type 'MutableRefObject<HTMLVideoElement>'.
>   Types of property 'current' are incompatible.
>     Type 'HTMLVideoElement | null' is not assignable to type 'HTMLVideoElement'.
>       Type 'null' is not assignable to type 'HTMLVideoElement'.ts(2322)

> Stream.d.ts(163, 5): The expected type comes from property 'streamRef' which is declared here on type 'IntrinsicAttributes & { streamRef?: MutableRefObject<HTMLVideoElement> | undefined; src: string; adUrl?: string | undefined; ... 33 more ...; onStreamAdTimeout?: EventListener | undefined; } & { ...; }'

Has anyone been able to implement this with TypeScript?

**Comment by michaellimair** [comment]
I think it's probably better to start your own thread, but try removing the `(null)` initializer on your useRef function @morkro, it should work fine

**Comment by tobiasbueschel** [comment]
@morkro this should fix the error that you're getting:

```js
const streamPlayerRef = useRef() as React.MutableRefObject<HTMLVideoElement>
```

**Comment by third774** [comment]
Hey y'all — a new version that addresses the `streamRef` type definition and adds it to the documented props.

[Example can be seen here](https://codesandbox.io/s/sleepy-kapitsa-wt0sj?file=/src/App.tsx)

Thanks for reporting!
