### ISSUE TITLE
Video is disappeared after fullscreen

### ISSUE THREAD

**Issue by iamrane** [cloudflare/stream-react#7]
When i'm using the default setup and enter fullscreen and then closes fullscreen the video is magically disappeared. I can still hear the sound.

Mac and chrome.

**Comment by third774** [comment]
Thanks for reporting! Working on getting a fix out ASAP. Will report back when that's live.

**Comment by third774** [comment]
This should be resolved.

**Comment by tobiasbueschel** [comment]
Hi @third774,

Thanks for looking into this - just curious, may I ask how it was resolved?
