### ISSUE TITLE
Remix Run Support?

### ISSUE THREAD

**Issue by emt-mocha** [cloudflare/stream-react#72]
I have tested the following plugin successfully with Gatsbyjs and Nextjs but unfortunately the plugin showing errors when using with Remix Run framework. The error only occur when I use Chrome Browser while click on fullscreen mode. Somehow other browsers such as Safari and Firefox no issues with fullscreen mode.

The error on chrome browser:
HTMLVideoElement.webkitEnterFullscreen() is deprecated. Please use Element.requestFullscreen() instead.

Some workaround and guide is appreciated.

Thank you,

**Comment by supachaidev** [comment]
> 

I've tried it. There is no problem now with remix@1.7.0.
