### ISSUE TITLE
Add customerCode prop to use a unique subdomain

### ISSUE THREAD

**Issue by supachaidev** [cloudflare/stream-react#73]
I have a commit ready to be merged.

https://github.com/cloudflare/stream-react/compare/master...supachaidev:stream-react:add-customer-code-prop

This change makes it easy to pass a customer code to the Stream component to use a unique subdomain for iframe source.

Please review and merge it.

Thank you.

**Comment by irvinebroque** [comment]
Thanks @supachaidev! Really appreciate this. PR here: https://github.com/cloudflare/stream-react/pull/74. We'll take a look.

**Comment by supachaidev** [comment]
Thank you for the merged PR 👍. When will the team release the new version on npm that includes the change?

**Comment by third774** [comment]
Sorry for the delay, this will be released soon!
