### ISSUE TITLE
Video does not load

### ISSUE THREAD

**Issue by PanJ** [cloudflare/stream-react#8]
I use this component to load the player but the video does not load as expected. The component has an iframe linked to `https://embed.videodelivery.net/embed/iframe.fla9.d42d30f.html?videoId=VIDEO_ID`. Accessing the URL directly also resulted in blank white page.

This is the code I use to load the video
```javascript
<Stream src={VIDEO_ID} width="100%" height="100%"></Stream>
```

**Comment by third774** [comment]
Hey there! 👋 Thanks for reporting this issue!

Accessing the URL resulting in a blank page is expected, but would you mind sharing an reproduction example on [codesandbox](https://codesandbox.io/)?

**Comment by PanJ** [comment]
@third774 Here is the URL to codesandbox.

https://codesandbox.io/s/5qzjc

**Comment by third774** [comment]
Awesome, thanks! May I ask which browser you are seeing this behavior in and whether you have any extensions installed?

**Comment by PanJ** [comment]
@third774 I was running on Chrome. Safari does not have any problem. Also, I've identified the Chrome add-on that causes the issue. Disabling the add-on solved the problem.

https://chrome.google.com/webstore/detail/pop-up-blocker-for-chrome/bkkbcggnhapdmkeljlodobbkopceiche?hl=en

Using iframe tag embedding (`https://iframe.videodelivery.net/$VIDEO_ID`) does not cause the issue. Maybe this is rather a bug than a feature?

**Comment by third774** [comment]
@PanJ unfortunately I'm not sure what their extension is doing or what behavior they think is something they want to mitigate. You might try reaching out to their support email address (support@poperblocker.com) and see if this is something they can look into.
