### ISSUE TITLE
abr manager / selectVariantTrack() warning

### ISSUE THREAD

**Issue by cengizdonmez** [cloudflare/stream-react#88]
Hello Cloudflare team,

Changing tracks while abr manager is enabled will likely result in the selected track being overriden. Consider disabling abr before calling selectVariantTrack().

I get a warning in the console for every video

<img width="1680" alt="SCR-20230707-rwc" src="https://github.com/cloudflare/stream-react/assets/64753658/b6b0b407-8440-4bec-8318-450e764c8aca">

**Comment by third774** [comment]
This should be fixed now! Thanks for reporting.
