### ISSUE TITLE
Ref doesn't work

### ISSUE THREAD

**Issue by potyoma** [cloudflare/stream-react#89]
Hello Cloudflare team,

I've encountered a problem using this library. Ref's don't work as expected. It has value, but the properties are 0 and actions like pause or play don't affect the player. Here is a working [demo](https://codesandbox.io/p/sandbox/stoic-lehmann-zs66mf?file=%2Fapp%2Fplayer.tsx%3A19%2C5).
next 13.4.12
react 18.2
@cloudflare/stream-react 1.8

Could you please have a look into this issue?

**Comment by potyoma** [comment]
upd: found the issue. i was passing the url, not the Id (can't provide it in the demo) and with id works just fine. though the doc says that both should work.

**Comment by third774** [comment]
Thanks for opening this issue! We've updated the docs to help clarify what value is expected.
