### ISSUE TITLE
Update to latest Stream player

### ISSUE THREAD

**Issue by tobiasbueschel** [cloudflare/stream-react#9]
Hi 👋 

Thanks for all your work on creating this React wrapper - much appreciated!

**I've seen this post in the Cloudflare forum:**

> Major Stream Player changes rolling out Aug 3, 2020
>
> Hello! I work on the Stream team and I wanted to share an upcoming Stream Player change that could impact developers who may be making customizations to the player DOM elements.
>
> You can stop reading if you aren’t making changes to the contents of the element or if you only use the official player API 68. Similarly, if you use the official React or Angular components, this change will not affect you.
> https://community.cloudflare.com/t/major-stream-player-changes-rolling-out-aug-3-2020/189844

**and noticed that `stream-react` still uses:**

https://github.com/cloudflare/stream-react/blob/11818c634e2d406a76faea1bd7f9cb3a0ab89623/src/Stream.tsx#L9-L10

While the forum post speaks about: [3f8m.fla9.latest.js](https://embed.cloudflarestream.com/embed/3f8m.fla9.latest.js) as the preview build, is there a specific reason why [r4xu.fla9.latest.js](https://embed.cloudflarestream.com/embed/r4xu.fla9.latest.js) is used instead of [sdk.latest.js](https://embed.cloudflarestream.com/embed/sdk.latest.js)?

---

On the same note, would be great if the Player would also be open sourced. This would make the version numbers more obvious and allow people to contribute to it :)

Cheers

**Comment by third774** [comment]
Hey there! `r4xu` is the evergreen version of the player, so no update is necessary to the `@cloudflare/stream-react` package to receive updates!

**Comment by third774** [comment]
To clarify, `r4xu.fla9.latest.js` is the script used with the legacy `<stream />` element embed. `sdk.latest.js` is the script for controlling the `<iframe />` embed, and we will at some point update this package to use the `<iframe />` embed instead of the `<stream />` embed.

Both scripts are evergreen and load the latest version of the player.

**Comment by serranoarevalo** [comment]
@third774  Thanks for your reply! Is there any difference between the iframe and the stream embed?

**Comment by third774** [comment]
@serranoarevalo under the hood, yes — though the API's are *very* similar.

The new player is now available for all!
