### ISSUE TITLE
The StreamPlayerApi type does not include a playbackRate property

### ISSUE THREAD

**Issue by gmldnjs26** [cloudflare/stream-react#92]
Hello Cloudflare team

I am currently customizing the control part of the player, and I am facing an issue where the playbackRate property is not recognized as part of the StreamPlayerApi type

<img width="692" alt="image" src="https://github.com/cloudflare/stream-react/assets/46416157/effee147-f798-4034-bd02-cc2153e10c37">

However, when I print out the instance of StreamPlayerApi, it does show that playbackRate exists

<img width="704" alt="스크린샷 2023-12-02 14 02 30" src="https://github.com/cloudflare/stream-react/assets/46416157/2d17259c-e7cd-4461-8853-e4f130f39716">

I would appreciate it if you could modify the type definition to include this property!

**Comment by third774** [comment]
Thanks for reporting! We'll get this added.
